package solution381to390;

import java.util.HashMap;

/**
 * Created by Xinzhuo Liu on 8/31/2016.
 * 389. Find the Difference  QuestionEditorial Solution  My Submissions
 Total Accepted: 8710
 Total Submissions: 17261
 Difficulty: Easy
 Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */
public class Solution389 {

    public char findTheDifference(String s, String t) {
        int result = 0;
        for (int i = 0; i <s.length() ; i++) {
            result -= s.charAt(i);
        }
        for (int i = 0; i <t.length() ; i++) {
            result += t.charAt(i);
        }
        return (char)(result);
    }
}
